apiVersion: v1
kind: Pod
metadata:
  name: qot-trafficbundle
spec:
  volumes:
  - name: shared-sockets
    emptyDir: {}
  containers:
  - name: qot-sync-service
    image: 770301640873.dkr.ecr.us-west-2.amazonaws.com/qot-sync-service:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: shared-sockets
      mountPath: /tmp
    command: ["/bin/bash","-c"]
    args: ["qot_sync_service -v"]
  - name: qot-timeline-service
    image: 770301640873.dkr.ecr.us-west-2.amazonaws.com/qot-timeline-service:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: shared-sockets
      mountPath: /tmp
    command: ["/bin/bash","-c"]
    args: ["qot_timeline_service"]
  - name: traffic-controller
    image: 770301640873.dkr.ecr.us-west-2.amazonaws.com/traffic-controller:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: shared-sockets
      mountPath: /tmp
  imagePullSecrets:
  - name: awstest
  